Repository aHaHaTeam/ShiroForbes, pull requests merged in 2024-08, with the labels that each got.

#33 Issue fixed
  src/main/kotlin/ru/shiroforbes/web/Router.kt
  src/main/resources/templates/thymeleaf/components/header.html
Labels: enhancement

#35 Issue fixed
  src/main/kotlin/ru/shiroforbes/web/Router.kt
Labels: enhancement

#41 investing hidden
  src/main/kotlin/ru/shiroforbes/web/Router.kt
  src/main/resources/templates/thymeleaf/profile.html
Labels: enhancement

#45 Marketplace
  src/main/kotlin/ru/shiroforbes/database/Init.kt
  src/main/kotlin/ru/shiroforbes/database/Offers.kt
  src/main/kotlin/ru/shiroforbes/model/Offer.kt
  src/main/kotlin/ru/shiroforbes/service/OfferService.kt
  src/main/kotlin/ru/shiroforbes/web/RatingUpdate.kt
  src/main/kotlin/ru/shiroforbes/web/Router.kt
  src/main/resources/static/scripts/marketplace.js
  src/main/resources/templates/thymeleaf/components/header.html
  src/main/resources/templates/thymeleaf/components/rating.html
  src/main/resources/templates/thymeleaf/components/rating_diff.html
  src/main/resources/templates/thymeleaf/marketplace.html
Labels: enhancement

#46 EMERGENCY fix to MAIN
  src/main/kotlin/ru/shiroforbes/database/Init.kt
Labels: bug, important

#43 Transaction history
  src/main/kotlin/ru/shiroforbes/config/AppConfig.kt
  src/main/kotlin/ru/shiroforbes/service/StudentService.kt
  src/main/kotlin/ru/shiroforbes/service/TransactionService.kt
  src/main/kotlin/ru/shiroforbes/web/Router.kt
  src/main/kotlin/ru/shiroforbes/web/TransactionUtil.kt
  src/main/resources/templates/thymeleaf/components/header.html
  src/main/resources/templates/thymeleaf/components/transactions.html
  src/main/resources/templates/thymeleaf/transactions_history.html
Labels: enhancement, help wanted, ОТ ДЮ

#54 UI
  src/main/kotlin/ru/shiroforbes/modules/googlesheets/RatingRow.kt
  src/main/kotlin/ru/shiroforbes/service/StudentService.kt
  src/main/kotlin/ru/shiroforbes/service/TransactionService.kt
  src/main/kotlin/ru/shiroforbes/web/RatingUpdate.kt
  src/main/kotlin/ru/shiroforbes/web/Router.kt
  src/main/resources/static/scripts/event.js
  src/main/resources/static/scripts/exercises.js
  src/main/resources/static/scripts/login.js
  src/main/resources/static/scripts/marketplace.js
  src/main/resources/static/scripts/transactions.js
  src/main/resources/static/scripts/update_rating.js
  src/main/resources/templates/thymeleaf/components/transactions.html
  src/main/resources/templates/thymeleaf/exercises.html
  src/main/resources/templates/thymeleaf/marketplace.html
  src/main/resources/templates/thymeleaf/profile.html
  src/main/resources/templates/thymeleaf/transactions.html
  src/main/resources/templates/thymeleaf/transactions_history.html
Labels: enhancement
